# Generated by Django 6.0.6 on 2026-08-08 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_type'),
        ('preparation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparation_items', to='events.event'),
        ),
    ]
