# Generated by Django 6.0.6 on 2026-08-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventtask_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Post-event notes, lessons learned, and improvements for future events.'),
        ),
    ]
