# Generated by Django 6.0.6 on 2026-09-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codrivers', '0007_remove_codriverprofile_drivers_and_more'),
        ('events', '0006_event_review_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='co_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='codrivers.codriverprofile'),
        ),
    ]
