# Generated by Django 6.0.6 on 2026-09-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_co_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed_co_driver_name',
            field=models.CharField(blank=True, max_length=101),
        ),
    ]
