# Generated by Django 6.0.6 on 2026-09-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_completed_co_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_role',
            field=models.CharField(choices=[('Competitor', 'Competitor'), ('Service Crew', 'Service Crew'), ('Spectator', 'Spectator'), ('Marshal', 'Marshal'), ('Other', 'Other')], default='Competitor', max_length=20),
        ),
    ]
