# Generated by Django 6.0.6 on 2026-09-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_attendance_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('12 Car', '12 Car Rally'), ('Road Rally', 'Road Rally'), ('Targa', 'Targa Rally'), ('Autosolo', 'Autosolo'), ('Autotest', 'Autotest'), ('Production Car Trial', 'Production Car Trial'), ('Sporting Trial', 'Sporting Trial'), ('Stage Rally', 'Stage Rally'), ('Hill Climb', 'Hill Climb'), ('Sprint', 'Sprint'), ('Track Day', 'Track Day'), ('Test Day', 'Test Day'), ('Navigational Scatter', 'Scatter Rally'), ('Treasure Hunt', 'Treasure Hunt'), ('Social', 'Club Social'), ('Training', 'Training'), ('Other', 'Other')], default='Road Rally', max_length=50)),
                ('organiser', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
