# Generated by Django 6.0.6 on 2026-09-27 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_sharedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shared_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_events', to='events.sharedevent'),
        ),
    ]
