# Generated by Django 6.0.6 on 2026-07-26 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='updated_on',
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.driverprofile')),
            ],
        ),
    ]
