# Generated by Django 6.0.6 on 2026-07-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine_size',
            field=models.PositiveIntegerField(),
        ),
    ]
