# Generated by Django 6.0.6 on 2026-07-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_remove_vehicle_image_vehicle_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(choices=[('Road', 'Road'), ('Historic', 'Historic'), ('Autotest', 'Autotest'), ('Autosolo', 'Autosolo'), ('Targa', 'Targa'), ('Stage', 'Stage')], default='Road', max_length=20),
        ),
    ]
