# Generated by Django 6.0.6 on 2026-09-09 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codrivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codriverprofile',
            name='display_name',
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='club_membership_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='motorsport_uk_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='codriverprofile',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
