# Generated by Django 6.0.6 on 2026-09-09 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codrivers', '0002_remove_codriverprofile_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoDriverEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='codrivers.codriverprofile')),
            ],
        ),
    ]
