# Generated by Django 6.0.6 on 2026-09-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_driverprofile_options_and_more'),
        ('codrivers', '0006_codriverprofile_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codriverprofile',
            name='drivers',
        ),
        migrations.AlterField(
            model_name='codriverprofile',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codrivers', to='accounts.driverprofile'),
        ),
    ]
